language: node_js
dist: trusty
node_js:
  - 5.2.0

cache:
  directories:
    - "$HOME/.meteor"
    - "$HOME/.npm"
    - "$HOME/node_modules"
    - ".meteor/local/build"
    - ".meteor/local/bundler-cache"
    - ".meteor/local/isopacks"
    - ".meteor/local/mirrors"
    - ".meteor/local/plugin-cache"
    - "node_modules"

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl -k https://install.meteor.com | sh; fi

install:
  - meteor npm install

script:
  # Test for JS errors
  - meteor npm run js-lint -- .
  # Run unit-tests
  - meteor npm run test
  # Run end-to-end tests
  - meteor npm run test-app
